import json

products_data = [
  {
    "id": "p1",
    "slug": "smart-maternity-bag",
    "name": "Smart Maternity Bag",
    "nameAr": "حقيبة الأمومة الذكية والعملية",
    "description": "Spacious and stylish diaper bag with thermal pockets.",
    "descriptionAr": "حقيبة أمومة عملية جداً بتصميم أنيق، تحتوي على جيوب حرارية لحفظ الحليب، ومساحة كبيرة لجميع أغراض طفلك. مثالية للأمهات.",
    "price": 249,
    "originalPrice": 350,
    "discount": 28,
    "images": ["/products/smart-maternity-bag.jpg"],
    "category": "cat-kids",
    "tags": ["أطفال", "حقيبة", "أمومة"],
    "rating": 4.9,
    "reviewCount": 112,
    "isNew": True,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["جيوب حرارية للحليب", "قماش مقاوم للماء", "سعة كبيرة وتصميم ذكي", "مريحة للحمل"],
    "specifications": { "الخامة": "مقاوم للماء", "الألوان": "وردي", "الاستخدام": "حقيبة أطفال" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p2",
    "slug": "classic-mens-watch",
    "name": "Classic Men's Watch",
    "nameAr": "ساعة رجالية كلاسيكية فاخرة",
    "description": "Elegant silver men's watch suitable for all occasions.",
    "descriptionAr": "ساعة رجالية باللون الفضي الأنيق، تصميم كلاسيكي جذاب يمنحك إطلالة راقية في المناسبات والعمل.",
    "price": 199,
    "originalPrice": 300,
    "discount": 33,
    "images": ["/products/classic-mens-watch.jpg"],
    "category": "cat-men",
    "tags": ["رجال", "ساعات", "أناقة"],
    "rating": 4.7,
    "reviewCount": 85,
    "isNew": False,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["مقاومة للماء", "حزام من الستانلس ستيل", "تصميم كلاسيكي فاخر", "بطارية تدوم طويلاً"],
    "specifications": { "اللون": "فضي", "الخامة": "ستانلس ستيل", "الضمان": "سنة" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p3",
    "slug": "ultra-smartwatch",
    "name": "Ultra Smartwatch",
    "nameAr": "الساعة الذكية الرياضية Ultra",
    "description": "Advanced smartwatch with health tracking and Bluetooth calling.",
    "descriptionAr": "ساعة ذكية متطورة بتصميم رياضي قوي، تدعم المكالمات عبر البلوتوث، وتتبع نبضات القلب والأنشطة الرياضية.",
    "price": 299,
    "originalPrice": 450,
    "discount": 33,
    "images": ["/products/ultra-smartwatch.jpg"],
    "category": "cat-electronics",
    "tags": ["إلكترونيات", "ساعات", "رياضة"],
    "rating": 4.8,
    "reviewCount": 210,
    "isNew": True,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["شاشة عالية الدقة", "تتبع نبضات القلب", "مكالمات بلوتوث", "أوضاع رياضية متعددة"],
    "specifications": { "البطارية": "أيام 3-5", "الشاشة": "لمس كامل", "التوافق": "iOS و Android" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p4",
    "slug": "women-bag-set",
    "name": "Women Bag Set",
    "nameAr": "طقم حقائب نسائية راقية (عدة قطع)",
    "description": "Elegant matching bag set for everyday use.",
    "descriptionAr": "طقم حقائب متناسق وأنيق، يلبي جميع احتياجاتك اليومية. تصميم عصري وجودة عالية للمرأة الأنيقة.",
    "price": 279,
    "originalPrice": 400,
    "discount": 30,
    "images": ["/products/women-bag-set.jpg"],
    "category": "cat-women",
    "tags": ["نساء", "حقائب", "موضة"],
    "rating": 4.6,
    "reviewCount": 94,
    "isNew": True,
    "isBestSeller": False,
    "isTrending": True,
    "features": ["طقم متكامل متعدد القطع", "جلد صناعي عالي الجودة", "ألوان متناسقة", "تصميم عملي وأنيق"],
    "specifications": { "العدد": "طقم متعدد", "الخامة": "جلد PU", "الاستخدام": "يومي ومناسبات" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p5",
    "slug": "stainless-steel-chopper",
    "name": "Stainless Steel Chopper",
    "nameAr": "هاشوار كهربائي من الإينوكس",
    "description": "Powerful meat and vegetable chopper with stainless steel bowl.",
    "descriptionAr": "طحانة ومفرمة كهربائية قوية بوعاء من الإينوكس المقاوم للصدأ. مثالية لفرم اللحوم وتقطيع الخضار في ثوانٍ معدودة.",
    "price": 189,
    "originalPrice": 250,
    "discount": 24,
    "images": ["/products/stainless-steel-chopper.jpg"],
    "category": "cat-home",
    "tags": ["مطبخ", "هاشوار", "أجهزة"],
    "rating": 4.9,
    "reviewCount": 320,
    "isNew": False,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["محرك قوي جداً", "شفرات حادة من الإينوكس", "سعة كبيرة 2-3 لتر", "سهلة التنظيف"],
    "specifications": { "الخامة": "إينوكس", "السرعات": "سرعتين", "القوة": "عالية" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p6",
    "slug": "gold-hair-clipper",
    "name": "Professional Hair Clipper",
    "nameAr": "آلة حلاقة احترافية للرجال (ذهبية)",
    "description": "Precise and stylish gold hair and beard clipper.",
    "descriptionAr": "ماكينة حلاقة وتشذيب احترافية بتصميم ذهبي رائع وزخارف جذابة. تضمن لك دقة عالية في الحلاقة وتحديد اللحية.",
    "price": 149,
    "originalPrice": 220,
    "discount": 32,
    "images": ["/products/gold-hair-clipper.jpg"],
    "category": "cat-men",
    "tags": ["رجال", "حلاقة", "عناية"],
    "rating": 4.7,
    "reviewCount": 160,
    "isNew": False,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["شفرات فولاذية حادة", "بطارية قابلة للشحن قابلة للإزالة", "تصميم مريح وأنيق", "أمشاط بدرجات مختلفة"],
    "specifications": { "اللون": "ذهبي", "الشحن": "USB", "الملحقات": "أمشاط وفرشاة" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p7",
    "slug": "smart-body-scale",
    "name": "Smart Body Scale",
    "nameAr": "ميزان ذكي لقياس الوزن والدهون",
    "description": "Digital smart scale that connects to your phone to track metrics.",
    "descriptionAr": "ميزان إلكتروني ذكي يتصل بالهاتف عبر تطبيق خاص، يقيس الوزن، نسبة الدهون، العضلات والماء في الجسم بدقة عالية.",
    "price": 159,
    "originalPrice": 250,
    "discount": 36,
    "images": ["/products/smart-body-scale.jpg"],
    "category": "cat-sport",
    "tags": ["صحة", "ميزان", "رياضة", "ذكي"],
    "rating": 4.8,
    "reviewCount": 125,
    "isNew": True,
    "isBestSeller": False,
    "isTrending": True,
    "features": ["قياس مؤشرات الجسم كاملة", "يتصل بتطبيق الهاتف", "تصميم زجاجي مقوى", "شاشة إضاءة واضحة"],
    "specifications": { "اللون": "أبيض", "التطبيق": "يدعم iOS و Android", "أقصى وزن": "180 كغ" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p8",
    "slug": "handheld-steam-iron",
    "name": "Handheld Steam Iron",
    "nameAr": "مكواة بخار يدوية محمولة",
    "description": "Fast and portable garment steamer for travel and home.",
    "descriptionAr": "مصلوح بخاري محمول وسريع التسخين، يزيل التجاعيد من الملابس بسهولة وسرعة. مثالي للسفر والاستخدام المنزلي السريع.",
    "price": 179,
    "originalPrice": 250,
    "discount": 28,
    "images": ["/products/handheld-steam-iron.jpg"],
    "category": "cat-home",
    "tags": ["منزل", "أجهزة", "ملابس"],
    "rating": 4.5,
    "reviewCount": 88,
    "isNew": False,
    "isBestSeller": False,
    "isTrending": True,
    "features": ["تسخين سريع في ثوانٍ", "خفيفة الوزن ومحمولة", "آمنة على جميع الأقمشة", "خزان ماء عملي"],
    "specifications": { "الاستخدام": "كي بالبخار", "النوع": "محمول يداً", "الطاقة": "ممتازة" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p9",
    "slug": "hair-straightener-comb",
    "name": "Hair Straightener Comb",
    "nameAr": "فرشاة حرارية لتسريح الشعر",
    "description": "Fast heating ceramic hair straightening brush.",
    "descriptionAr": "مشط حراري بديل للسشوار، يسرح الشعر ويجعله ناعماً وحريرياً في دقائق بفضل تقنية السيراميك الآمنة على الشعر.",
    "price": 139,
    "originalPrice": 200,
    "discount": 30,
    "images": ["/products/hair-straightener-comb.jpg"],
    "category": "cat-women",
    "tags": ["نساء", "عناية_بالشعر", "جمال"],
    "rating": 4.8,
    "reviewCount": 210,
    "isNew": False,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["تقنية السيراميك لحماية الشعر", "تسخين سريع", "درجات حرارة قابلة للتعديل", "تمنع تطاير الشعر"],
    "specifications": { "التقنية": "حرارة سيراميك", "اللون": "أسود/أحمر", "الاستخدام": "لجميع أنواع الشعر" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p10",
    "slug": "electric-neck-massager",
    "name": "Electric Neck Massager",
    "nameAr": "جهاز تدليك الرقبة والكتفين",
    "description": "Shiatsu neck and back massager with heat function.",
    "descriptionAr": "جهاز مساج كهربائي للرقبة والظهر يوفر تدليكاً عميقاً ومريحاً، مع خاصية التسخين لتخفيف تشنجات العضلات والتوتر.",
    "price": 229,
    "originalPrice": 350,
    "discount": 34,
    "images": ["/products/electric-neck-massager.jpg"],
    "category": "cat-home",
    "tags": ["صحة", "مساج", "راحة"],
    "rating": 4.9,
    "reviewCount": 180,
    "isNew": True,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["تدليك شياتسو عميق", "خاصية التسخين الحراري", "يمكن استخدامه للظهر والأرجل", "سهل الاستخدام في المنزل والسيارة"],
    "specifications": { "الاستخدام": "تدليك الجسم", "الطاقة": "كهرباء", "الوظائف": "دوران مزدوج" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p11",
    "slug": "mens-white-sneakers",
    "name": "Men's White Sneakers",
    "nameAr": "حذاء رياضي رجالي أبيض مريح",
    "description": "Stylish and comfortable white sneakers for everyday wear.",
    "descriptionAr": "سبرديلة رجالية باللون الأبيض، مريحة جداً للمشي والاستخدام اليومي. تصميم عصري يناسب جميع الإطلالات الكاجوال.",
    "price": 189,
    "originalPrice": 280,
    "discount": 32,
    "images": ["/products/mens-white-sneakers.jpg"],
    "category": "cat-men",
    "tags": ["رجال", "أحذية", "رياضة"],
    "rating": 4.6,
    "reviewCount": 115,
    "isNew": False,
    "isBestSeller": False,
    "isTrending": True,
    "features": ["نعل طبي مريح", "قماش يسمح بالتهوية", "تصميم أنيق وعصري", "خفيف الوزن"],
    "specifications": { "اللون": "أبيض", "المقاسات": "39-44", "الاستخدام": "كاجوال / مشي" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p12",
    "slug": "food-vacuum-sealer",
    "name": "Food Vacuum Sealer",
    "nameAr": "آلة تغليف وحفظ الأطعمة بالتفريغ",
    "description": "Compact vacuum sealer machine to keep food fresh longer.",
    "descriptionAr": "آلة سحب الهواء وتغليف الأطعمة، تحافظ على طراوة الطعام لمدة أطول بـ 5 مرات وتوفر مساحة في الثلاجة.",
    "price": 169,
    "originalPrice": 250,
    "discount": 32,
    "images": ["/products/food-vacuum-sealer.jpg"],
    "category": "cat-home",
    "tags": ["مطبخ", "حفظ", "أجهزة"],
    "rating": 4.7,
    "reviewCount": 140,
    "isNew": True,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["سحب هواء قوي", "سهلة الاستخدام بزر واحد", "تطيل عمر الطعام", "تأتي مع أكياس مجانية"],
    "specifications": { "الاستخدام": "تغليف حراري وتفريغ", "اللون": "أسود", "الملحقات": "أكياس تغليف" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p13",
    "slug": "portable-car-vacuum-new",
    "name": "Portable Car Vacuum",
    "nameAr": "مكنسة كهربائية محمولة للسيارة",
    "description": "High power handheld vacuum cleaner for car interior.",
    "descriptionAr": "أسپيراتور صغير ومحمول للسيارة، قوة شفط عالية لتنظيف المقاعد والزوايا الضيقة بسهولة وفعالية.",
    "price": 149,
    "originalPrice": 220,
    "discount": 32,
    "images": ["/products/portable-car-vacuum-new.jpg"],
    "category": "cat-electronics",
    "tags": ["سيارة", "تنظيف", "أجهزة"],
    "rating": 4.5,
    "reviewCount": 96,
    "isNew": False,
    "isBestSeller": False,
    "isTrending": True,
    "features": ["قوة شفط ممتازة", "تصميم مضغوط وخفيف", "تعمل على ولاعة السيارة أو قابلة للشحن", "تصل للأماكن الصعبة"],
    "specifications": { "النوع": "محمول", "الاستخدام": "للسيارة والمنزل", "الفلتر": "قابل للغسل" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p14",
    "slug": "flawless-hair-remover",
    "name": "Painless Hair Remover",
    "nameAr": "قلم إزالة شعر الوجه بدون ألم",
    "description": "Flawless facial hair remover for women, smooth and painless.",
    "descriptionAr": "جهاز بحجم القلم لإزالة شعر الوجه الزغب بلطف وبدون أي ألم أو احمرار. آمن تماماً على جميع أنواع البشرة.",
    "price": 129,
    "originalPrice": 180,
    "discount": 28,
    "images": ["/products/flawless-hair-remover.jpg"],
    "category": "cat-women",
    "tags": ["نساء", "جمال", "عناية"],
    "rating": 4.8,
    "reviewCount": 260,
    "isNew": False,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["إزالة شعر دقيقة وبدون ألم", "تصميم أنيق بحجم القلم", "إضاءة LED مدمجة للرؤية", "لا يسبب حساسية"],
    "specifications": { "الاستخدام": "للوجه", "اللون": "أبيض/ذهبي", "الطاقة": "بطارية قابلة للشحن" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p15",
    "slug": "mens-beard-trimmer",
    "name": "Men's Beard Trimmer",
    "nameAr": "ماكينة حلاقة وتشذيب اللحية",
    "description": "Precision beard trimmer for men with multiple combs.",
    "descriptionAr": "تونذوز احترافية للرجال لتحديد وتشذيب اللحية بدقة عالية. تصميم عملي مريح مع شفرات حادة تدوم طويلاً.",
    "price": 139,
    "originalPrice": 200,
    "discount": 30,
    "images": ["/products/mens-beard-trimmer.jpg"],
    "category": "cat-men",
    "tags": ["رجال", "حلاقة", "عناية"],
    "rating": 4.6,
    "reviewCount": 134,
    "isNew": False,
    "isBestSeller": False,
    "isTrending": True,
    "features": ["شفرات آمنة وحادة", "أمشاط تحديد بمقاسات مختلفة", "بطارية جيدة", "سهلة التنظيف"],
    "specifications": { "النوع": "تشذيب اللحية", "اللون": "أسود", "الملحقات": "زيت، فرشاة، أمشاط" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p16",
    "slug": "elegant-womens-handbag",
    "name": "Elegant Women's Handbag",
    "nameAr": "حقيبة يد نسائية أنيقة",
    "description": "Chic and modern handbag for women, perfect for outings.",
    "descriptionAr": "صاك نسائي أنيق جداً بتصميم عصري يناسب الخروجات اليومية والمناسبات الخفيفة. يضيف لمسة سحرية لإطلالتك.",
    "price": 199,
    "originalPrice": 280,
    "discount": 29,
    "images": ["/products/elegant-womens-handbag.jpg"],
    "category": "cat-women",
    "tags": ["نساء", "حقائب", "أناقة"],
    "rating": 4.7,
    "reviewCount": 75,
    "isNew": True,
    "isBestSeller": False,
    "isTrending": True,
    "features": ["تصميم عصري وجذاب", "مساحة داخلية جيدة", "جلد ممتاز مقاوم للخدش", "تفاصيل معدنية أنيقة"],
    "specifications": { "الخامة": "جلد PU", "النمط": "حقيبة كتف / يد", "المقاس": "متوسط" },
    "inStock": True,
    "codAvailable": True
  },
  {
    "id": "p17",
    "slug": "triple-barrel-hair-curler",
    "name": "Triple Barrel Hair Curler",
    "nameAr": "جهاز تجعيد الشعر الاحترافي المموج",
    "description": "Professional 3-barrel hair waver for beautiful beach waves.",
    "descriptionAr": "فير تجعيد الشعر الثلاثي الأسطوانات، يمنحك تموجات طبيعية وجميلة (Beach Waves) في دقائق معدودة وبكل سهولة بالمنزل.",
    "price": 159,
    "originalPrice": 240,
    "discount": 33,
    "images": ["/products/triple-barrel-hair-curler.jpg"],
    "category": "cat-women",
    "tags": ["نساء", "عناية_بالشعر", "جمال"],
    "rating": 4.8,
    "reviewCount": 195,
    "isNew": False,
    "isBestSeller": True,
    "isTrending": True,
    "features": ["تموجات شعر طبيعية وسريعة", "سيراميك لحماية الشعر", "درجتي حرارة للتحكم", "مناسب لجميع أنواع الشعر"],
    "specifications": { "التقنية": "سيراميك تورمالين", "الحرارة": "تصل لـ 210 درجة", "الأسطوانات": "3 أسطوانات" },
    "inStock": True,
    "codAvailable": True
  }
]

ts_code = """import type { Product, Review } from "@/lib/types";

export const products: Product[] = """ + json.dumps(products_data, ensure_ascii=False, indent=2) + """;

export function getTrending(limit = 6): Product[] {
  return products.filter((p) => p.isTrending).slice(0, limit);
}

export function getBestSellers(limit = 8): Product[] {
  return products.filter((p) => p.isBestSeller).slice(0, limit);
}

export function getNewArrivals(limit = 8): Product[] {
  return products.filter((p) => p.isNew).slice(0, limit);
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(productId: string, limit = 4): Product[] {
  const currentProduct = products.find((p) => p.id === productId);
  if (!currentProduct) return [];

  return products
    .filter((p) => p.id !== productId && p.category === currentProduct.category)
    .slice(0, limit);
}

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "p1",
    userName: "مريم ب.",
    rating: 5,
    comment: "صاك واعر بزاف وعملي، فيه بلايص فين ندير الرضاعات وهز ليا كاع حوايج البيبي. شكرا لكم التوصيل كان سريع.",
    date: "2024-05-12",
    verifiedPurchase: true,
  },
  {
    id: "r2",
    productId: "p3",
    userName: "ياسين أ.",
    rating: 5,
    comment: "المكانة جاتني كيف ما فالصورة، زوينة والبطارية كتدوم مزيان.",
    date: "2024-05-10",
    verifiedPurchase: true,
  },
  {
    id: "r3",
    productId: "p5",
    userName: "خديجة م.",
    rating: 4,
    comment: "الهاشوار مجهد كيطحن اللحم والخضرة دغيا. الثمن مناسب جداً مقارنة مع الجودة.",
    date: "2024-05-08",
    verifiedPurchase: true,
  },
  {
    id: "r4",
    productId: "p9",
    userName: "سارة ك.",
    rating: 5,
    comment: "المشطة الحرارية زوينة بزاف، كتصاوب الشعر دغيا خصوصا الا كنتي مزروبة للخدمة.",
    date: "2024-05-05",
    verifiedPurchase: true,
  },
];

export function getProductReviews(productId: string): Review[] {
  return reviews.filter((r) => r.productId === productId);
}

export function getTrendingProducts(): Product[] {
  return getTrending(8);
}
"""

with open("/Users/omarouhaddou/Desktop/vs code test/src/lib/data/products.ts", "w", encoding="utf-8") as f:
    f.write(ts_code)

print("Generated products.ts with correct visual matching data.")
